/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DBQueryModel
 */
export interface DBQueryModel {
    /**
     * 
     * @type {string}
     * @memberof DBQueryModel
     */
    queryId?: string;
    /**
     * 
     * @type {string}
     * @memberof DBQueryModel
     */
    userId?: string;
    /**
     * 
     * @type {number}
     * @memberof DBQueryModel
     */
    createTime?: number;
    /**
     * 
     * @type {number}
     * @memberof DBQueryModel
     */
    ttl?: number;
    /**
     * 
     * @type {string}
     * @memberof DBQueryModel
     */
    queryText: string;
    /**
     * 
     * @type {string}
     * @memberof DBQueryModel
     */
    answerText?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DBQueryModel
     */
    sources?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof DBQueryModel
     */
    isComplete?: boolean;
}

/**
 * Check if a given object implements the DBQueryModel interface.
 */
export function instanceOfDBQueryModel(value: object): value is DBQueryModel {
    if (!('queryText' in value) || value['queryText'] === undefined) return false;
    return true;
}

export function DBQueryModelFromJSON(json: any): DBQueryModel {
    return DBQueryModelFromJSONTyped(json, false);
}

export function DBQueryModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DBQueryModel {
    if (json == null) {
        return json;
    }
    return {
        
        'queryId': json['query_id'] == null ? undefined : json['query_id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'createTime': json['create_time'] == null ? undefined : json['create_time'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
        'queryText': json['query_text'],
        'answerText': json['answer_text'] == null ? undefined : json['answer_text'],
        'sources': json['sources'] == null ? undefined : json['sources'],
        'isComplete': json['is_complete'] == null ? undefined : json['is_complete'],
    };
}

export function DBQueryModelToJSON(value?: DBQueryModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'query_id': value['queryId'],
        'user_id': value['userId'],
        'create_time': value['createTime'],
        'ttl': value['ttl'],
        'query_text': value['queryText'],
        'answer_text': value['answerText'],
        'sources': value['sources'],
        'is_complete': value['isComplete'],
    };
}

