/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DBQueryModel model module.
 * @module model/DBQueryModel
 * @version 0.1.0
 */
class DBQueryModel {
    /**
     * Constructs a new <code>DBQueryModel</code>.
     * @alias module:model/DBQueryModel
     * @param queryText {String} 
     */
    constructor(queryText) { 
        
        DBQueryModel.initialize(this, queryText);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, queryText) { 
        obj['query_text'] = queryText;
    }

    /**
     * Constructs a <code>DBQueryModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DBQueryModel} obj Optional instance to populate.
     * @return {module:model/DBQueryModel} The populated <code>DBQueryModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DBQueryModel();

            if (data.hasOwnProperty('query_id')) {
                obj['query_id'] = ApiClient.convertToType(data['query_id'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('create_time')) {
                obj['create_time'] = ApiClient.convertToType(data['create_time'], 'Number');
            }
            if (data.hasOwnProperty('ttl')) {
                obj['ttl'] = ApiClient.convertToType(data['ttl'], 'Number');
            }
            if (data.hasOwnProperty('query_text')) {
                obj['query_text'] = ApiClient.convertToType(data['query_text'], 'String');
            }
            if (data.hasOwnProperty('answer_text')) {
                obj['answer_text'] = ApiClient.convertToType(data['answer_text'], 'String');
            }
            if (data.hasOwnProperty('sources')) {
                obj['sources'] = ApiClient.convertToType(data['sources'], ['String']);
            }
            if (data.hasOwnProperty('is_complete')) {
                obj['is_complete'] = ApiClient.convertToType(data['is_complete'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DBQueryModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DBQueryModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DBQueryModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['query_id'] && !(typeof data['query_id'] === 'string' || data['query_id'] instanceof String)) {
            throw new Error("Expected the field `query_id` to be a primitive type in the JSON string but got " + data['query_id']);
        }
        // ensure the json data is a string
        if (data['user_id'] && !(typeof data['user_id'] === 'string' || data['user_id'] instanceof String)) {
            throw new Error("Expected the field `user_id` to be a primitive type in the JSON string but got " + data['user_id']);
        }
        // ensure the json data is a string
        if (data['query_text'] && !(typeof data['query_text'] === 'string' || data['query_text'] instanceof String)) {
            throw new Error("Expected the field `query_text` to be a primitive type in the JSON string but got " + data['query_text']);
        }
        // ensure the json data is a string
        if (data['answer_text'] && !(typeof data['answer_text'] === 'string' || data['answer_text'] instanceof String)) {
            throw new Error("Expected the field `answer_text` to be a primitive type in the JSON string but got " + data['answer_text']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['sources'])) {
            throw new Error("Expected the field `sources` to be an array in the JSON data but got " + data['sources']);
        }

        return true;
    }


}

DBQueryModel.RequiredProperties = ["query_text"];

/**
 * @member {String} query_id
 */
DBQueryModel.prototype['query_id'] = undefined;

/**
 * @member {String} user_id
 * @default 'unknown'
 */
DBQueryModel.prototype['user_id'] = 'unknown';

/**
 * @member {Number} create_time
 */
DBQueryModel.prototype['create_time'] = undefined;

/**
 * @member {Number} ttl
 */
DBQueryModel.prototype['ttl'] = undefined;

/**
 * @member {String} query_text
 */
DBQueryModel.prototype['query_text'] = undefined;

/**
 * @member {String} answer_text
 */
DBQueryModel.prototype['answer_text'] = undefined;

/**
 * @member {Array.<String>} sources
 */
DBQueryModel.prototype['sources'] = undefined;

/**
 * @member {Boolean} is_complete
 * @default false
 */
DBQueryModel.prototype['is_complete'] = false;






export default DBQueryModel;

