/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubmitQueryRequest model module.
 * @module model/SubmitQueryRequest
 * @version 0.1.0
 */
class SubmitQueryRequest {
    /**
     * Constructs a new <code>SubmitQueryRequest</code>.
     * @alias module:model/SubmitQueryRequest
     * @param queryText {String} 
     */
    constructor(queryText) { 
        
        SubmitQueryRequest.initialize(this, queryText);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, queryText) { 
        obj['query_text'] = queryText;
    }

    /**
     * Constructs a <code>SubmitQueryRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubmitQueryRequest} obj Optional instance to populate.
     * @return {module:model/SubmitQueryRequest} The populated <code>SubmitQueryRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubmitQueryRequest();

            if (data.hasOwnProperty('query_text')) {
                obj['query_text'] = ApiClient.convertToType(data['query_text'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubmitQueryRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubmitQueryRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SubmitQueryRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['query_text'] && !(typeof data['query_text'] === 'string' || data['query_text'] instanceof String)) {
            throw new Error("Expected the field `query_text` to be a primitive type in the JSON string but got " + data['query_text']);
        }
        // ensure the json data is a string
        if (data['user_id'] && !(typeof data['user_id'] === 'string' || data['user_id'] instanceof String)) {
            throw new Error("Expected the field `user_id` to be a primitive type in the JSON string but got " + data['user_id']);
        }

        return true;
    }


}

SubmitQueryRequest.RequiredProperties = ["query_text"];

/**
 * @member {String} query_text
 */
SubmitQueryRequest.prototype['query_text'] = undefined;

/**
 * @member {String} user_id
 */
SubmitQueryRequest.prototype['user_id'] = undefined;






export default SubmitQueryRequest;

