/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.DBQueryModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DBQueryModel', function() {
    it('should create an instance of DBQueryModel', function() {
      // uncomment below and update the code to test DBQueryModel
      //var instance = new FastApi.DBQueryModel();
      //expect(instance).to.be.a(FastApi.DBQueryModel);
    });

    it('should have the property queryId (base name: "query_id")', function() {
      // uncomment below and update the code to test the property queryId
      //var instance = new FastApi.DBQueryModel();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new FastApi.DBQueryModel();
      //expect(instance).to.be();
    });

    it('should have the property createTime (base name: "create_time")', function() {
      // uncomment below and update the code to test the property createTime
      //var instance = new FastApi.DBQueryModel();
      //expect(instance).to.be();
    });

    it('should have the property ttl (base name: "ttl")', function() {
      // uncomment below and update the code to test the property ttl
      //var instance = new FastApi.DBQueryModel();
      //expect(instance).to.be();
    });

    it('should have the property queryText (base name: "query_text")', function() {
      // uncomment below and update the code to test the property queryText
      //var instance = new FastApi.DBQueryModel();
      //expect(instance).to.be();
    });

    it('should have the property answerText (base name: "answer_text")', function() {
      // uncomment below and update the code to test the property answerText
      //var instance = new FastApi.DBQueryModel();
      //expect(instance).to.be();
    });

    it('should have the property sources (base name: "sources")', function() {
      // uncomment below and update the code to test the property sources
      //var instance = new FastApi.DBQueryModel();
      //expect(instance).to.be();
    });

    it('should have the property isComplete (base name: "is_complete")', function() {
      // uncomment below and update the code to test the property isComplete
      //var instance = new FastApi.DBQueryModel();
      //expect(instance).to.be();
    });

  });

}));
